// Package coreapi is a generated client for the Entire Core API — the
// control plane that manages identity, orgs, projects, repos, mirrors,
// and service accounts.
//
// The oas_*.go files are generated by ogen from spec/core.gen.json (the
// normalised spec produced by spec/normalize.go from the pristine
// upstream spec/core.openapi.json). Do not edit them by hand. To refresh:
//
//	curl -fsSL https://us.console.entire.io/api/v1/openapi.json \
//	    -o internal/coreapi/spec/core.openapi.json
//	go generate ./internal/coreapi/...
//
// The hand-written authenticated constructor and error helpers live in
// client.go alongside the generated code.
package coreapi

//go:generate go run spec/normalize.go
//go:generate go run github.com/ogen-go/ogen/cmd/ogen@v1.20.3 --target . --package coreapi --config ogen.yml --clean spec/core.gen.json
