// Code generated by ogen, DO NOT EDIT.

package coreapi

// AddOrgMemberParams is parameters of addOrgMember operation.
type AddOrgMemberParams struct {
	OrgId string
}

// CreateBindingParams is parameters of createBinding operation.
type CreateBindingParams struct {
	AccountId string
}

// DeleteBindingParams is parameters of deleteBinding operation.
type DeleteBindingParams struct {
	AccountId string
	BindingId string
}

// DeleteMirrorParams is parameters of deleteMirror operation.
type DeleteMirrorParams struct {
	Provider DeleteMirrorProvider
	Owner    string
	Repo     string
	// Public host of the cluster serving the mirror.
	ClusterHost string
}

// DeleteRepoParams is parameters of deleteRepo operation.
type DeleteRepoParams struct {
	RepoId string
}

// DeleteServiceAccountParams is parameters of deleteServiceAccount operation.
type DeleteServiceAccountParams struct {
	AccountId string
}

// GetMirrorParams is parameters of getMirror operation.
type GetMirrorParams struct {
	MirrorId string
}

// GetPermissionsParams is parameters of getPermissions operation.
type GetPermissionsParams struct {
	ResourceType string
	ResourceId   string
	// If set, return the SpiceDB trace for this permission instead of the permission list.
	Explain OptString `json:",omitempty,omitzero"`
}

// GetRepoParams is parameters of getRepo operation.
type GetRepoParams struct {
	RepoId string
}

// GetServiceAccountParams is parameters of getServiceAccount operation.
type GetServiceAccountParams struct {
	AccountId string
}

// GrantProjectAccessParams is parameters of grantProjectAccess operation.
type GrantProjectAccessParams struct {
	ProjectId string
}

// GrantRepoAccessParams is parameters of grantRepoAccess operation.
type GrantRepoAccessParams struct {
	RepoId string
}

// GrantServiceAccountAccessParams is parameters of grantServiceAccountAccess operation.
type GrantServiceAccountAccessParams struct {
	AccountId string
}

// ListBindingsParams is parameters of listBindings operation.
type ListBindingsParams struct {
	AccountId string
}

// ListMirrorsParams is parameters of listMirrors operation.
type ListMirrorsParams struct {
	// Optional: restrict to mirrors on this cluster (public host, e.g. royalcanin.partial.to).
	Cluster OptString `json:",omitempty,omitzero"`
	// Optional: restrict to mirrors of this upstream provider (e.g. "github").
	Provider OptString `json:",omitempty,omitzero"`
	// Optional: restrict to mirrors with this upstream owner login.
	Owner OptString `json:",omitempty,omitzero"`
}

// ListOrgMembersParams is parameters of listOrgMembers operation.
type ListOrgMembersParams struct {
	OrgId string
}

// ListOrgProjectsParams is parameters of listOrgProjects operation.
type ListOrgProjectsParams struct {
	OrgId string
}

// ListProjectMembersParams is parameters of listProjectMembers operation.
type ListProjectMembersParams struct {
	ProjectId string
}

// ListProjectReposParams is parameters of listProjectRepos operation.
type ListProjectReposParams struct {
	ProjectId string
}

// ListProjectsParams is parameters of listProjects operation.
type ListProjectsParams struct {
	// Optional: exact-match project name.
	Name OptString `json:",omitempty,omitzero"`
}

// ListServiceAccountGrantsParams is parameters of listServiceAccountGrants operation.
type ListServiceAccountGrantsParams struct {
	AccountId string
}

// ListServiceAccountsParams is parameters of listServiceAccounts operation.
type ListServiceAccountsParams struct {
	OrgId string
}

// LookupResourcesParams is parameters of lookupResources operation.
type LookupResourcesParams struct {
	// SpiceDB resource type (e.g. "repo", "project", "org").
	ResourceType string
	// Optional: only list resources where the caller has this permission.
	Permission OptString `json:",omitempty,omitzero"`
}

// RemoveOrgMemberParams is parameters of removeOrgMember operation.
type RemoveOrgMemberParams struct {
	OrgId          string
	Provider       string
	ProviderUserId string
}

// ResolveHandleParams is parameters of resolveHandle operation.
type ResolveHandleParams struct {
	// IdP slug (e.g. "github").
	Provider string
	// User-visible handle at the provider.
	Handle string
}

// RevokeProjectAccessParams is parameters of revokeProjectAccess operation.
type RevokeProjectAccessParams struct {
	ProjectId   string
	GranteeType string
	GranteeId   string
}

// RevokeProjectAccessByProviderParams is parameters of revokeProjectAccessByProvider operation.
type RevokeProjectAccessByProviderParams struct {
	ProjectId      string
	Provider       string
	ProviderUserId string
}

// RevokeServiceAccountAccessParams is parameters of revokeServiceAccountAccess operation.
type RevokeServiceAccountAccessParams struct {
	AccountId    string
	ResourceType RevokeServiceAccountAccessResourceType
	ResourceId   string
}
