// Code generated by ogen, DO NOT EDIT.

package coreapi

// OperationName is the ogen operation name
type OperationName = string

const (
	AddOrgMemberOperation                  OperationName = "AddOrgMember"
	BatchLookupOperation                   OperationName = "BatchLookup"
	CreateBindingOperation                 OperationName = "CreateBinding"
	CreateMirrorOperation                  OperationName = "CreateMirror"
	CreateOrgOperation                     OperationName = "CreateOrg"
	CreateProjectOperation                 OperationName = "CreateProject"
	CreateRepoOperation                    OperationName = "CreateRepo"
	CreateServiceAccountOperation          OperationName = "CreateServiceAccount"
	DeleteBindingOperation                 OperationName = "DeleteBinding"
	DeleteMirrorOperation                  OperationName = "DeleteMirror"
	DeleteRepoOperation                    OperationName = "DeleteRepo"
	DeleteServiceAccountOperation          OperationName = "DeleteServiceAccount"
	GetMeOperation                         OperationName = "GetMe"
	GetMirrorOperation                     OperationName = "GetMirror"
	GetPermissionsOperation                OperationName = "GetPermissions"
	GetRepoOperation                       OperationName = "GetRepo"
	GetServiceAccountOperation             OperationName = "GetServiceAccount"
	GrantProjectAccessOperation            OperationName = "GrantProjectAccess"
	GrantRepoAccessOperation               OperationName = "GrantRepoAccess"
	GrantServiceAccountAccessOperation     OperationName = "GrantServiceAccountAccess"
	ListAuditEventsOperation               OperationName = "ListAuditEvents"
	ListBindingsOperation                  OperationName = "ListBindings"
	ListMirrorsOperation                   OperationName = "ListMirrors"
	ListOIDCProvidersOperation             OperationName = "ListOIDCProviders"
	ListOrgMembersOperation                OperationName = "ListOrgMembers"
	ListOrgProjectsOperation               OperationName = "ListOrgProjects"
	ListOrgsOperation                      OperationName = "ListOrgs"
	ListProjectMembersOperation            OperationName = "ListProjectMembers"
	ListProjectReposOperation              OperationName = "ListProjectRepos"
	ListProjectsOperation                  OperationName = "ListProjects"
	ListServiceAccountGrantsOperation      OperationName = "ListServiceAccountGrants"
	ListServiceAccountsOperation           OperationName = "ListServiceAccounts"
	LookupResourcesOperation               OperationName = "LookupResources"
	RemoveOrgMemberOperation               OperationName = "RemoveOrgMember"
	ResolveHandleOperation                 OperationName = "ResolveHandle"
	RevokeProjectAccessOperation           OperationName = "RevokeProjectAccess"
	RevokeProjectAccessByProviderOperation OperationName = "RevokeProjectAccessByProvider"
	RevokeServiceAccountAccessOperation    OperationName = "RevokeServiceAccountAccess"
)
