#!/usr/bin/env bash
#MISE description="Install binaries into ~/go/bin"

set -eu

export GOBIN=${GOPATH:-$HOME/go}/bin
echo "NOTE: we're overriding \$GOBIN: $GOBIN" 1>&2

commands=(
  entire
  git-remote-entire
)

for c in "${commands[@]}"; do
  go install "./cmd/$c"
  echo "Installed: '$c'" 1>&2
done
